# Form implementation generated from reading ui file './ui/kp_gain.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_kp_setting_dialog(object):
    def setupUi(self, kp_setting_dialog):
        kp_setting_dialog.setObjectName("kp_setting_dialog")
        kp_setting_dialog.resize(498, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=kp_setting_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 260, 471, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=kp_setting_dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 471, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(26)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.unit_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.unit_label.setObjectName("unit_label")
        self.horizontalLayout_2.addWidget(self.unit_label)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(14, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.current_value_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.current_value_label.setObjectName("current_value_label")
        self.horizontalLayout.addWidget(self.current_value_label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(kp_setting_dialog)
        self.buttonBox.accepted.connect(kp_setting_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(kp_setting_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(kp_setting_dialog)

    def retranslateUi(self, kp_setting_dialog):
        _translate = QtCore.QCoreApplication.translate
        kp_setting_dialog.setWindowTitle(_translate("kp_setting_dialog", "Setting"))
        self.label.setText(_translate("kp_setting_dialog", "PID position loop gain:determines the strength of the controller\'s response to the\n"
" current error signal, which is the difference between the desired setpoint and the\n"
" actual process variable."))
        self.label_3.setText(_translate("kp_setting_dialog", "Unit"))
        self.unit_label.setText(_translate("kp_setting_dialog", "-"))
        self.label_2.setText(_translate("kp_setting_dialog", "Proportional (P):"))
        self.current_value_label.setText(_translate("kp_setting_dialog", "-"))
