# Form implementation generated from reading ui file './ui/torq_cmd_limiter.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_torq_cmd_limiter_dialog(object):
    def setupUi(self, torq_cmd_limiter_dialog):
        torq_cmd_limiter_dialog.setObjectName("torq_cmd_limiter_dialog")
        torq_cmd_limiter_dialog.resize(413, 314)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=torq_cmd_limiter_dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 391, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.unit_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.unit_label.setObjectName("unit_label")
        self.horizontalLayout_2.addWidget(self.unit_label)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(14, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.current_value_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.current_value_label.setObjectName("current_value_label")
        self.horizontalLayout.addWidget(self.current_value_label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=torq_cmd_limiter_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 371, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(torq_cmd_limiter_dialog)
        self.buttonBox.accepted.connect(torq_cmd_limiter_dialog.accept)
        self.buttonBox.rejected.connect(torq_cmd_limiter_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(torq_cmd_limiter_dialog)

    def retranslateUi(self, torq_cmd_limiter_dialog):
        _translate = QtCore.QCoreApplication.translate
        torq_cmd_limiter_dialog.setWindowTitle(_translate("torq_cmd_limiter_dialog", "Setting"))
        self.label.setText(_translate("torq_cmd_limiter_dialog", "Torque command limiter"))
        self.label_4.setText(_translate("torq_cmd_limiter_dialog", "Unit:"))
        self.unit_label.setText(_translate("torq_cmd_limiter_dialog", "-"))
        self.label_2.setText(_translate("torq_cmd_limiter_dialog", "limit: "))
        self.current_value_label.setText(_translate("torq_cmd_limiter_dialog", "-"))
